### ISSUE TITLE
Debian 8 x64中安装gor错误

### ISSUE THREAD

**Issue by alairs** [wendal/gor#100]
由于没有linux 64编译版，自己安装，出现错误如下，何解？

root@hkvps:~# export GOPATH=/root/gopath
root@hkvps:~# go get -u github.com/wendal/gor
root@hkvps:~# go install github.com/wendal/gor/gor
gopath/src/github.com/wendal/gor/gor/gor.go:8:2: cannot find package "github.com/howeyc/fsnotify" in any of:
        /usr/lib/go/src/pkg/github.com/howeyc/fsnotify (from $GOROOT)
        /root/gopath/src/github.com/howeyc/fsnotify (from $GOPATH)

**Comment by wendal** [comment]
got get github.com/howeyc/fsnotify

试试
