### ISSUE TITLE
安装到子目录时sitemap与rss网址出错

### ISSUE THREAD

**Issue by whzecomjm** [wendal/gor#107]
如果将gor安装到类似于 `http://example.com/blog` 这样的子目录中，生成的rss和sitemap文件中的网址都会重复出现 `blog`，即 `http://example.com/blog/blog/...`

**Comment by wendal** [comment]
我检查一下

**Comment by whzecomjm** [comment]
@wendal 可以帮忙生成一个新的 win-32 的exe么？

**Comment by wendal** [comment]
可以, 稍等

**Comment by wendal** [comment]
链接：http://pan.baidu.com/s/1jHmKbMe 密码：as89

**Comment by whzecomjm** [comment]
谢谢！
