### ISSUE TITLE
panic: runtime error: assignment to entry in nil map

### ISSUE THREAD

**Issue by alairs** [wendal/gor#89]
panic: runtime error: assignment to entry in nil map

goroutine 1 [running]:
github.com/wendal/gor.func路006(0x5b0a80, 0x11a81a20, 0x172, 0x5b0a80
        /opt/gopath/src/github.com/wendal/gor/compile.go:312 +0x2b7
github.com/wendal/mustache.(*SectionNode).Render(0x11ac7480, 0x11af02
0a0, 0x11af00e0, 0x11ae5060, ...)
        /opt/gopath/src/github.com/wendal/mustache/node.go:79 +0x364

刚gor new后就可以gor compile,但是设置完config和site，添加完文章后，gor compile就会报错

**Comment by wendal** [comment]
你博客的源码有放在github吗? 地址发一个?

**Comment by alairs** [comment]
没有放github 我打包给你看看




From: Wendal Chen
Date: 2015-07-21 10:02
To: wendal/gor
CC: 阿泉
Subject: Re: [gor] panic: runtime error: assignment to entry in nil map (#89)
你博客的源码有放在github吗? 地址发一个?

**Comment by alairs** [comment]
源码我打包了，帮忙看看 http://zjq.in/zjqin.zip @wendal

**Comment by wendal** [comment]
我试试

**Comment by wendal** [comment]
找到原因, site.yml引用的 readme.md 而 文件名称写错为 reame.md

在3de75dd80bf46e5ad8db209fa0cbfb23bd67c0ea 中加入了提示.

**Comment by alairs** [comment]
thanks @wendal
