### ISSUE TITLE
rss与siemap里面有一大堆css内容，这是怎么会事儿？

### ISSUE THREAD

**Issue by alairs** [wendal/gor#90]
rss.xml与sitemap.xml 底部有一大堆CSS内容，提交Google Sitemap时有错误提示，请问怎么会事儿？

另： 网站更换域名另，请更新一下 阿泉来咧 <http://ltecn.com>

**Comment by wendal** [comment]
没发现这个问题

http://wendal.net/rss.xml

http://wendal.net/sitemap.xml

**Comment by wendal** [comment]
打开你的博客看sitemap.xml也没看到css

**Comment by alairs** [comment]
@wendal  哎，排查了 ，是我的chrome问题，不知道时那个插件作祟，其他浏览器都OK
