### ISSUE TITLE
能不能添加多说评论，开启https后disqus好像不显示了

### ISSUE THREAD

**Issue by alairs** [wendal/gor#92]
能不能添加多说评论，开启https后disqus好像不显示了

**Comment by wendal** [comment]
开Chrome控制台看看有啥报错

**Comment by alairs** [comment]
@wendal 

chrome控制态提示错误如下，意思http://ltecn.disqus.com/embed.js未用https传输，然后直接浏览http://ltecn.disqus.com/embed.js就会302定向到https://a.disquscdn.com/embed.js，但是gor没开放disqus源码文件，无法修改。

另外，firefox浏览时会提示非安全内容，手动通过后就可以disqus了,chrome没有这个功能，何解?

Mixed Content: The page at 'https://ltecn.com/acs/put-raspberry-pi-data-to-lewei50.html' was loaded over HTTPS, but requested an insecure script 'http://ltecn.disqus.com/embed.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by wendal** [comment]
哦,直接改改源码好了

**Comment by wendal** [comment]
多说? 有啊
