### ISSUE TITLE
怎样将新建文章的图片都存到media 文件夹下面，而不是一篇文章一个图片文件夹

### ISSUE THREAD

**Issue by webfd** [wendal/gor#94]

**Comment by webfd** [comment]
http://wendal.net/assets/media/2013/10/28/IMG_0857.JPG 和你博客的一样的类型

**Comment by webfd** [comment]
我的是这一种样式的
http://127.0.0.1:8080/assets/media/2015-08-18-bei-jing/13123123123213123.jpg

**Comment by wendal** [comment]
额, 自己建文件夹就好了

**Comment by webfd** [comment]
我 所建的文件夹 是 2015-08-18-bei-jing 而不是跟你博客的一样/2013/10/28/

**Comment by wendal** [comment]
没懂你的意思, 那些文件夹都是自己建的啊

**Comment by webfd** [comment]
我在根media 文件夹下放了三张图片 ，然后用gor new "bei jing " media 生成一篇博客后， 
保存图片的 文件不是按照时间格式（/2013/10/28/）存在，而是按照 2015-08-18-bei-jing 这种文件夹存的，
这个是consloe 给的提示
2015/08/19 08:43:18 post.go:54: imgtag = <img src="%s" alt="" width="600">
2015/08/19 08:43:18 post.go:54: urlperfix = {{urls.media}}/
2015/08/19 08:43:18 post.go:54: localdir = media/
2015/08/19 08:43:18 post.go:46: Create Post at posts/2015-08-19-bei-jing.md
0 <img src="{{urls.media}}/2015-08-19-bei-jing/.gitkeep" alt="" width="600">
1 <img src="{{urls.media}}/2015-08-19-bei-jing/13123123123213123.jpg" alt="" width="600">
2 <img src="{{urls.media}}/2015-08-19-bei-jing/20140530143030_298.png" alt="" width="600">
3 <img src="{{urls.media}}/2015-08-19-bei-jing/20140530143046_893.png" alt="" width="600">
4 <img src="{{urls.media}}/2015-08-19-bei-jing/20150101211544_310.gif" alt="" width="600">

**Comment by wendal** [comment]
哦,那是, 自动移动过去的功能

**Comment by wendal** [comment]
我看看怎么加个选项

**Comment by wendal** [comment]
用这样写就好了, 不需要加最后面的media

```
gor new "bei jing"
```

**Comment by webfd** [comment]
`gor new "bei jing " media` media 是要移动的图片 ，编译后， 他的路径 是`/2013/10/28/`  要比`/2015-08-19-bei-jing/`这种的 好些

**Comment by webfd** [comment]
算了 ，我自己改post 里面的代码，把功能改成我想要的得了

**Comment by wendal** [comment]
哦, 改完发个pull req吧
