### ISSUE TITLE
如何修改日期格式

### ISSUE THREAD

**Issue by whzecomjm** [wendal/gor#96]
默认的格式是带时分秒的，我不想要，怎么修改？有没有 DateForm 之类的可用选项？

**Comment by wendal** [comment]
哪里的格式?

**Comment by whzecomjm** [comment]
你好，archive 里的时间格式，默认太长 不需要。

**Comment by whzecomjm** [comment]
注： 我的 .md 文件中 写的时间里有时分秒，但是是之前hexo自动生成的

**Comment by wendal** [comment]
还不明白你指哪个时间

网站的源码在github上吗? 我看看

**Comment by wendal** [comment]
哦, 我知道了

**Comment by wendal** [comment]
.md文件里面的date, 自己改一下应该不麻烦吧?

**Comment by whzecomjm** [comment]
好吧 我自己把100多篇时间都删了。。。 不过要是能自动只显示 “年月日”就好了，或者能自定义时间格式。

**Comment by whzecomjm** [comment]
除此之外，很喜欢这款博客程序，生成速度快，该有的也有了，也能自定义不少。感谢提供。以下博客站点已经用Gor部署上：

 <http://cn.whzecomjm.com/>
- <http://en.whzecomjm.com/>

**Comment by whzecomjm** [comment]
对了 要是`gor http` 能默认先运行 `gor compile` 并且有 watch 功能就好了。

**Comment by wendal** [comment]
gor preview

**Comment by whzecomjm** [comment]
多谢，那挺好。不过你文档中都没有写上去。
